### ISSUE TITLE
https://huggingface.co/  这个平台好像挂了 cc 不运行 做不了隧道

### ISSUE THREAD

**Issue by lovelves** [mjjonone/mjj-docker#3]
![image](https://github.com/mjjonone/mjj-docker/assets/25540718/dc933a04-f357-4af0-884c-8b3c21abceb8)

**Comment by mqzgithub1203** [comment]
在huggingface.co这个上面使用dockfile，如何修改为固定隧道使用

**Comment by mjjonone** [comment]
可以的，再次试试
